# Generated by Django 4.0.3 on 2022-06-14 18:06

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item_categories',
            },
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ImageField(default=0, upload_to='')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item_images',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('availability', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=256, null=True)),
                ('rec_price', models.IntegerField(default=0, null=True)),
                ('attrs', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, to='items.itemcategory')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stock')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
