# Generated by Django 4.0.3 on 2022-06-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemimages_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='attrs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
