# Generated by Django 4.0.3 on 2022-05-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='filename',
            field=models.ImageField(upload_to='items'),
        ),
    ]
