# Generated by Django 4.0.3 on 2022-06-10 10:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimages',
            name='filename',
        ),
        migrations.AddField(
            model_name='itemimages',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
