# Generated by Django 4.0.3 on 2022-06-14 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_itemimages_filename_itemimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
