# Generated by Django 4.0.3 on 2022-05-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stocktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stocktype'),
        ),
    ]
