# Generated by Django 4.0.3 on 2022-05-23 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_stock_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='manager',
        ),
        migrations.AddField(
            model_name='stock',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
