# Generated by Django 4.0.3 on 2022-05-23 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0004_remove_stock_manager_stock_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
