# Generated by Django 4.0.3 on 2022-05-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stock_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='type_id',
            new_name='type',
        ),
    ]
